from .borne import build_borne_section
from .imprimante import build_imprimante_section
from .emmento import build_emmento_section
from .horaires import build_horaires_section
from .systeme import build_systeme_section
from .notifications import build_notifications_section
from .apparence import build_apparence_section
from .mise_a_jour import build_mise_a_jour_section
from .animation_impression import build_animation_section
from .led import build_led_section
